name    'erwbgy-anthillpro'
version '0.2.0'
source 'https://github.com/erwbgy/puppet-anthillpro.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Install an AnthillPro agent'
description 'Install and basic configuration of an AnthillPro agent'
project_page 'http://forge.puppetlabs.com/erwbgy/anthillpro'
